version: '3'

services:
  frontend:
    build:
      context: ./menu-system-ui/menu-system/Dockerfile  # Caminho para o diretório front-end
    ports:
      - "80:80"  # Porta 80 disponível para o FRONTEND
    networks:
      - app-network

  backend:
    build:
      context: ./menu-system-api/Dockerfile  # Caminho para o diretório do seu back-end Spring Boot
    ports:
      - "8080:8080"  # Porta 8080 disponível para o BACKEND
    networks:
      - app-network
    # environment:
    #  - SPRING_PROFILES_ACTIVE=prod

networks:
  app-network:
    driver: bridge
